const els={total:document.querySelector('#metricTotal'),actions:document.querySelector('#metricActions'),ready:document.querySelector('#metricReady'),nts:document.querySelector('#metricNts'),decisionGrid:document.querySelector('#decisionGrid'),readyList:document.querySelector('#readyList'),gapList:document.querySelector('#gapListOpenai'),projectList:document.querySelector('#projectList'),ntsList:document.querySelector('#ntsList'),search:document.querySelector('#searchInputOpenai'),chips:[...document.querySelectorAll('[data-filter]')]};
let projects=[];let mode='all';
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const norm=v=>String(v||'').trim().toLowerCase().replaceAll('ё','е');
function val(row,names){const map=Object.fromEntries(Object.entries(row).map(([k,v])=>[norm(k),v]));for(const n of names){const v=map[norm(n)];if(v!==undefined&&String(v).trim())return v}return''}
function pct(v){const m=String(v||'').replace(',','.').match(/\d+(\.\d+)?/);return m?Math.max(0,Math.min(100,Math.round(Number(m[0])))):0}
function iso(v){const raw=String(v||'').trim();const serial=raw.match(/^\d+(?:\.0+)?$/);if(serial){const d=parseInt(serial[0],10);if(d>20000&&d<60000)return new Date(Date.UTC(1899,11,30+d)).toISOString().slice(0,10)}return /^\d{4}-\d{2}-\d{2}$/.test(raw)?raw:''}
function dateText(v){if(!v)return'нет срока';try{return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(v+'T00:00:00'))}catch{return'нет срока'}}
function normalizeProject(row,i){const readiness=pct(val(row,['Готовность пакета','Готовность','readiness']));return{uid:val(row,['ID'])||`p-${i}`,name:val(row,['Проект','Название'])||'Без названия',direction:val(row,['Направление','Контур']),priority:val(row,['Приоритет']),stage:val(row,['Стадия']),owner:val(row,['Ответственный']),grant:val(row,['Маршрут финансирования','Грант']),window:val(row,['Ближайшее окно']),next:val(row,['Следующее действие']),deadline:iso(val(row,['Срок'])),readiness,status:val(row,['Статус'])||'статус не указан',note:val(row,['Блокер / примечание','Комментарий'])}}
function issues(p){const out=[];if(!p.owner)out.push(['Ответственный','Назначить ответственного','red']);if(!p.next)out.push(['Следующее действие','Определить ближайший шаг','amber']);if(!p.grant)out.push(['Грант','Выбрать маршрут финансирования','amber']);if(!p.deadline)out.push(['Срок','Поставить контрольный срок','amber']);if(norm(p.note).match(/необходимо|риск|блок|нет|требует/))out.push(['Риск','Разобрать блокер','red']);return out}
function actionItems(){return projects.map(p=>{const iss=issues(p);if(!iss.length)return null;const red=iss.some(i=>i[2]==='red');return{p,iss,score:(red?0:1)+(p.deadline?0:.5),tone:red?'red':'amber'}}).filter(Boolean).sort((a,b)=>a.score-b.score).slice(0,5)}
function filtered(){const q=norm(els.search.value);return projects.filter(p=>{if(q&&!norm([p.name,p.owner,p.grant,p.direction,p.status].join(' ')).includes(q))return false;if(mode==='risk'&&!issues(p).length)return false;if(mode==='ready'&&p.readiness<70)return false;return true})}
function render(){const actions=actionItems();const ready=projects.filter(p=>p.readiness>=70).sort((a,b)=>b.readiness-a.readiness);const nts=projects.filter(p=>issues(p).length||norm(p.status).includes('нтс')).slice(0,9);els.total.textContent=projects.length;els.actions.textContent=projects.filter(p=>issues(p).length).length;els.ready.textContent=ready.length;els.nts.textContent=nts.length;els.decisionGrid.innerHTML=actions.map((it,i)=>`<article class="decision-card"><span class="num">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(it.p.name)}</h3><p>${esc(it.iss[0][1])}</p></div><footer><span class="tag ${it.tone}">${esc(it.iss[0][0])}</span><span class="tag">${esc(dateText(it.p.deadline))}</span></footer></article>`).join('')||empty('Срочных решений нет','Критические действия не выявлены.');els.readyList.innerHTML=ready.slice(0,5).map(p=>item(p.name,`${p.readiness}% · ${p.grant||'маршрут уточнить'}`)).join('')||empty('Нет готовых проектов','Нужна доупаковка паспортов.');const gaps=projects.map(p=>({p,g:issues(p)})).filter(x=>x.g.length).sort((a,b)=>b.g.length-a.g.length).slice(0,5);els.gapList.innerHTML=gaps.map(x=>item(x.p.name,x.g.map(i=>i[0]).join(', '))).join('');renderProjects();els.ntsList.innerHTML=nts.map(p=>`<article class="compact-item"><strong>${esc(p.name)}</strong><span>${esc(p.next||p.note||'Вынести на обсуждение')}</span></article>`).join('')}
function item(a,b){return`<div class="compact-item"><strong>${esc(a)}</strong><span>${esc(b)}</span></div>`}function empty(a,b){return`<div class="compact-item"><strong>${esc(a)}</strong><span>${esc(b)}</span></div>`}
function renderProjects(){const list=filtered().slice(0,41);els.projectList.innerHTML=list.map(p=>`<article class="project-row"><div class="project-title"><strong>${esc(p.name)}</strong><span>${esc(p.direction||p.stage||'направление не указано')}</span></div><div><small>Ответственный</small>${esc(p.owner||'не указан')}</div><div><small>Маршрут</small>${esc(p.grant||'не выбран')}</div><div><small>${p.readiness}%</small><div class="progress"><i style="width:${p.readiness}%"></i></div></div></article>`).join('')||empty('Ничего не найдено','Измените поиск или фильтр.')}
async function init(){try{const data=await fetch('data/fallback-dashboard.json',{cache:'no-store'}).then(r=>r.json());projects=(data.projects||[]).map(normalizeProject).filter(p=>p.name&&p.name!=='Без названия');render()}catch(e){els.decisionGrid.innerHTML=empty('Не удалось загрузить данные','Проверьте data/fallback-dashboard.json.')}}
els.search.addEventListener('input',renderProjects);els.chips.forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.filter;els.chips.forEach(x=>x.classList.toggle('is-active',x===b));renderProjects()}));init();
