const els={total:document.querySelector('#metricTotal'),actions:document.querySelector('#metricActions'),ready:document.querySelector('#metricReady'),nts:document.querySelector('#metricNts'),decisionGrid:document.querySelector('#decisionGrid'),readyList:document.querySelector('#readyList'),gapList:document.querySelector('#gapListOpenai'),projectList:document.querySelector('#projectList'),ntsList:document.querySelector('#ntsList'),search:document.querySelector('#searchInputOpenai')};
let projects=[];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const norm=v=>String(v||'').trim().toLowerCase().replaceAll('ё','е');
function val(row,names){const map=Object.fromEntries(Object.entries(row).map(([k,v])=>[norm(k),v]));for(const n of names){const v=map[norm(n)];if(v!==undefined&&String(v).trim())return v}return''}
function pct(v){const m=String(v||'').replace(',','.').match(/\d+(\.\d+)?/);return m?Math.max(0,Math.min(100,Math.round(Number(m[0])))):0}
function iso(v){const raw=String(v||'').trim();const serial=raw.match(/^\d+(?:\.0+)?$/);if(serial){const d=parseInt(serial[0],10);if(d>20000&&d<60000)return new Date(Date.UTC(1899,11,30+d)).toISOString().slice(0,10)}if(/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw;return''}
function dateText(v){if(!v)return'нет срока';try{return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(v+'T00:00:00'))}catch{return'нет срока'}}
function normalizeProject(row,i){const readiness=pct(val(row,['Готовность пакета','Готовность','readiness']));return{uid:val(row,['ID'])||`p-${i}`,name:val(row,['Проект','Название'])||'Без названия',direction:val(row,['Направление','Контур']),priority:val(row,['Приоритет']),stage:val(row,['Стадия']),owner:val(row,['Ответственный']),grant:val(row,['Маршрут финансирования','Грант']),window:val(row,['Ближайшее окно']),next:val(row,['Следующее действие']),deadline:iso(val(row,['Срок'])),readiness,status:val(row,['Статус'])||'статус не указан',note:val(row,['Блокер / примечание','Комментарий'])}}
function issues(p){const out=[];if(!p.owner)out.push(['Ответственный','Назначить ответственного','red']);if(!p.next)out.push(['Следующее действие','Определить ближайший шаг','amber']);if(!p.grant)out.push(['Грант','Выбрать маршрут финансирования','amber']);if(!p.deadline)out.push(['Срок','Поставить контрольный срок','amber']);if(norm(p.note).match(/необходимо|риск|блок|нет|требует/))out.push(['Риск','Разобрать блокер','red']);return out}
function actionItems(){return projects.map(p=>{const iss=issues(p);if(!iss.length)return null;const red=iss.some(i=>i[2]==='red');return{p,iss,score:(red?0:1)+(p.deadline?0:.5),tone:red?'red':'amber'}}).filter(Boolean).sort((a,b)=>a.score-b.score).slice(0,5)}
function render(){const actions=actionItems();const ready=projects.filter(p=>p.readiness>=70).sort((a,b)=>b.readiness-a.readiness);const nts=projects.filter(p=>issues(p).length||norm(p.status).includes('нтс')).slice(0,9);els.total.textContent=projects.length;els.actions.textContent=actions.length;els.ready.textContent=ready.length;els.nts.textContent=nts.length;els.decisionGrid.innerHTML=actions.map((it,i)=>`<article class="decision-card"><span class="num">${String(i+1).padStart(2,'0')}</span><h3>${esc(it.p.name)}</h3><p>${esc(it.iss[0][1])}</p><footer><span class="tag ${it.tone}">${esc(it.iss.map(x=>x[0]).join(', '))}</span><span class="tag">${esc(dateText(it.p.deadline))}</span></footer></article>`).join('')||'<div class="compact-item"><strong>Срочных решений нет</strong><span>По текущим данным критические действия не выявлены.</span></div>';els.readyList.innerHTML=ready.slice(0,6).map(p=>`<div class="compact-item"><strong>${esc(p.name)}</strong><span>${p.readiness}% · ${esc(p.grant||'маршрут уточнить')}</span></div>`).join('')||'<div class="compact-item"><strong>Нет готовых проектов</strong><span>Нужна доупаковка паспортов.</span></div>';const gaps=projects.map(p=>({p,g:issues(p)})).filter(x=>x.g.length).sort((a,b)=>b.g.length-a.g.length).slice(0,6);els.gapList.innerHTML=gaps.map(x=>`<div class="compact-item"><strong>${esc(x.p.name)}</strong><span>${esc(x.g.map(i=>i[0]).join(', '))}</span></div>`).join('');renderProjects();els.ntsList.innerHTML=nts.map(p=>`<article class="compact-item"><strong>${esc(p.name)}</strong><span>${esc(p.next||p.note||'Вынести на обсуждение')}</span></article>`).join('')}
function renderProjects(){const q=norm(els.search.value);const list=projects.filter(p=>!q||norm([p.name,p.owner,p.grant,p.direction,p.status].join(' ')).includes(q)).slice(0,41);els.projectList.innerHTML=list.map(p=>`<article class="project-row"><div class="project-title"><strong>${esc(p.name)}</strong><span>${esc(p.direction||p.stage||'направление не указано')}</span></div><div><small>Ответственный</small>${esc(p.owner||'не указан')}</div><div><small>Маршрут</small>${esc(p.grant||'не выбран')}</div><div><small>${p.readiness}%</small><div class="progress"><i style="width:${p.readiness}%"></i></div></div></article>`).join('')}
async function init(){try{const data=await fetch('data/fallback-dashboard.json',{cache:'no-store'}).then(r=>r.json());projects=(data.projects||[]).map(normalizeProject).filter(p=>p.name&&p.name!=='Без названия');render()}catch(e){els.decisionGrid.innerHTML='<div class="compact-item"><strong>Не удалось загрузить данные</strong><span>Проверьте data/fallback-dashboard.json.</span></div>'}}
els.search.addEventListener('input',renderProjects);init();
